<Project Sdk="Aspire.AppHost.Sdk/13.6.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>dd1b6125-bc3b-4fe0-b68c-bfee4f6ea88b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RateLimiting.Server\RateLimiting.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.6.0" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.6.0" />
  </ItemGroup>
</Project>
